version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: 0000
    ports:
      - 3306:3306

  backend:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
