spring:
  datasource:
    url: jdbc:mysql://localhost:3306/treetree
    username: tree
    password: tree0226
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  ssl:
    enabled: true
    key-store: /home/letsencrypt.jks
    key-store-password: yummy2021
    key-password: yummy2021
